// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsCrawler.Persistence.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewsCrawler.Persistence.Postgres.Migrations
{
    [DbContext(typeof(PostgresNewsArticleContext))]
    [Migration("20200509152700_AddedArticleCompression")]
    partial class AddedArticleCompression
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleCleanedContentId");

                    b.Property<int?>("ArticleContentId");

                    b.Property<int>("CleanedContentLength");

                    b.Property<int>("ContentLength");

                    b.Property<bool>("IsIndexPage");

                    b.Property<DateTimeOffset?>("PublishedDate");

                    b.Property<DateTimeOffset>("RecordedDate");

                    b.Property<int?>("SourceId");

                    b.Property<string>("Title")
                        .HasMaxLength(250);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("ArticleCleanedContentId");

                    b.HasIndex("ArticleContentId");

                    b.HasIndex("SourceId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.ArticleCleanedContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CleanedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArticleCleanedContent");
                });

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.ArticleContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("CompressedContent");

                    b.Property<int>("CompressionType");

                    b.Property<string>("TextContent")
                        .HasColumnName("Content")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArticleContent");
                });

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.WordCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("NewsSource")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("WordCount");
                });

            modelBuilder.Entity("NewsCrawler.Persistence.Postgres.Article", b =>
                {
                    b.HasOne("NewsCrawler.Persistence.Postgres.ArticleCleanedContent", "ArticleCleanedContent")
                        .WithMany()
                        .HasForeignKey("ArticleCleanedContentId");

                    b.HasOne("NewsCrawler.Persistence.Postgres.ArticleContent", "ArticleContent")
                        .WithMany()
                        .HasForeignKey("ArticleContentId");

                    b.HasOne("NewsCrawler.Persistence.Postgres.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });
#pragma warning restore 612, 618
        }
    }
}
